<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="40" result="Failed" total="40" passed="0" failed="40" inconclusive="0" skipped="0" asserts="0" engine-version="3.2.1.0" clr-version="4.0.30319.42000" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:28:21Z" duration="194.187301">
  <command-line><![CDATA["C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe"  /out=TestResult.txt /result=TestResult.xml /framework=net-4.0 MathOperations.AcceptanceTests\bin\Debug\AccptanceTests.dll]]></command-line>
  <test-suite type="Assembly" id="0-1050" name="AccptanceTests.dll" fullname="C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\bin\Debug\AccptanceTests.dll" runstate="Runnable" testcasecount="40" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:28:21Z" duration="193.855613" total="40" passed="0" failed="40" inconclusive="0" skipped="0" asserts="0">
    <environment framework-version="3.0.5797.27534" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.10586.0" platform="Win32NT" cwd="C:\Users\Federito\Cursos\BddBelax\MathOperations" machine-name="FEDERICO" user="Federito" user-domain="FEDERICO" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="RuntimeFramework" value="net-4.0" />
      <setting name="WorkDirectory" value="C:\Users\Federito\Cursos\BddBelax\MathOperations" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="8" />
    </settings>
    <properties>
      <property name="_PID" value="4468" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1051" name="AccptanceTests" fullname="AccptanceTests" runstate="Runnable" testcasecount="40" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:28:21Z" duration="193.833836" total="40" passed="0" failed="40" inconclusive="0" skipped="0" asserts="0">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1054" name="Api" fullname="AccptanceTests.Api" runstate="Runnable" testcasecount="20" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:25:51Z" duration="43.755790" total="20" passed="0" failed="20" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestSuite" id="0-1055" name="Features" fullname="AccptanceTests.Api.Features" runstate="Runnable" testcasecount="20" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:25:51Z" duration="43.755764" total="20" passed="0" failed="20" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-suite type="TestFixture" id="0-1025" name="ApiOperationsFeature" fullname="AccptanceTests.Api.Features.ApiOperationsFeature" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" testcasecount="20" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:25:51Z" duration="43.751391" total="20" passed="0" failed="20" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Api Operations" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-suite type="ParameterizedMethod" id="0-1032" name="AddTwoNumbersApi" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2016-06-07 18:25:08Z" end-time="2016-06-07 18:25:22Z" duration="14.295641" total="6" passed="0" failed="6" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Add two numbers api" />
                <property name="Category" value="api" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1026" name="AddTwoNumbersApi(&quot;12&quot;,&quot;5&quot;,&quot;17&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(&quot;12&quot;,&quot;5&quot;,&quot;17&quot;,System.String[])" methodname="AddTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1580158007" result="Failed" label="Error" start-time="2016-06-07 18:25:08Z" end-time="2016-06-07 18:25:12Z" duration="4.076417" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 11]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 12 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("12") (0.0s)
And I have set 5 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("5") (0.0s)
When I send the "add" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 17 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1027" name="AddTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;-25&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;-25&quot;,System.String[])" methodname="AddTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="292299438" result="Failed" label="Error" start-time="2016-06-07 18:25:12Z" end-time="2016-06-07 18:25:14Z" duration="2.023599" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 11]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -20 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-20") (0.0s)
And I have set -5 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-5") (0.0s)
When I send the "add" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -25 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1028" name="AddTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;177&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;177&quot;,System.String[])" methodname="AddTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1542415269" result="Failed" label="Error" start-time="2016-06-07 18:25:14Z" end-time="2016-06-07 18:25:16Z" duration="2.017853" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 11]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 180 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("180") (0.0s)
And I have set -3 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-3") (0.0s)
When I send the "add" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 177 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1029" name="AddTwoNumbersApi(&quot;-24&quot;,&quot;32&quot;,&quot;8&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(&quot;-24&quot;,&quot;32&quot;,&quot;8&quot;,System.String[])" methodname="AddTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1002758134" result="Failed" label="Error" start-time="2016-06-07 18:25:16Z" end-time="2016-06-07 18:25:18Z" duration="2.018573" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 11]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -24 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-24") (0.0s)
And I have set 32 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("32") (0.0s)
When I send the "add" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 8 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1030" name="AddTwoNumbersApi(&quot;-1123&quot;,&quot;2&quot;,&quot;-1121&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(&quot;-1123&quot;,&quot;2&quot;,&quot;-1121&quot;,System.String[])" methodname="AddTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="596653663" result="Failed" label="Error" start-time="2016-06-07 18:25:18Z" end-time="2016-06-07 18:25:20Z" duration="2.116005" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 11]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -1123 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-1123") (0.0s)
And I have set 2 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("2") (0.0s)
When I send the "add" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -1121 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1031" name="AddTwoNumbersApi(&quot;2512&quot;,&quot;51&quot;,&quot;2563&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(&quot;2512&quot;,&quot;51&quot;,&quot;2563&quot;,System.String[])" methodname="AddTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="79304597" result="Failed" label="Error" start-time="2016-06-07 18:25:20Z" end-time="2016-06-07 18:25:22Z" duration="2.021476" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.AddTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 11]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 2512 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("2512") (0.0s)
And I have set 51 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("51") (0.0s)
When I send the "add" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 2563 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
            <test-suite type="ParameterizedMethod" id="0-1044" name="DivideTwoNumbersApi" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-06-07 18:25:22Z" end-time="2016-06-07 18:25:31Z" duration="8.120215" total="4" passed="0" failed="4" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Divide two numbers api" />
                <property name="Category" value="api" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1040" name="DivideTwoNumbersApi(&quot;12&quot;,&quot;6&quot;,&quot;2&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(&quot;12&quot;,&quot;6&quot;,&quot;2&quot;,System.String[])" methodname="DivideTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1069402004" result="Failed" label="Error" start-time="2016-06-07 18:25:22Z" end-time="2016-06-07 18:25:24Z" duration="2.021521" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 44]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 12 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("12") (0.0s)
And I have set 6 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("6") (0.0s)
When I send the "divide" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 2 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1041" name="DivideTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;4&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;4&quot;,System.String[])" methodname="DivideTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="142881592" result="Failed" label="Error" start-time="2016-06-07 18:25:24Z" end-time="2016-06-07 18:25:26Z" duration="2.063578" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 44]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -20 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-20") (0.0s)
And I have set -5 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-5") (0.0s)
When I send the "divide" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 4 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1042" name="DivideTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;-60&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;-60&quot;,System.String[])" methodname="DivideTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1448988997" result="Failed" label="Error" start-time="2016-06-07 18:25:26Z" end-time="2016-06-07 18:25:29Z" duration="2.016749" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 44]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 180 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("180") (0.0s)
And I have set -3 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-3") (0.0s)
When I send the "divide" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -60 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1043" name="DivideTwoNumbersApi(&quot;-8&quot;,&quot;2&quot;,&quot;-4&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(&quot;-8&quot;,&quot;2&quot;,&quot;-4&quot;,System.String[])" methodname="DivideTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1637476819" result="Failed" label="Error" start-time="2016-06-07 18:25:29Z" end-time="2016-06-07 18:25:31Z" duration="2.017028" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.DivideTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 44]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -8 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-8") (0.0s)
And I have set 2 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("2") (0.0s)
When I send the "divide" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -4 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
            <test-suite type="ParameterizedMethod" id="0-1049" name="MultiplyTwoNumbersApi" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-06-07 18:25:31Z" end-time="2016-06-07 18:25:39Z" duration="8.075395" total="4" passed="0" failed="4" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Multiply two numbers api" />
                <property name="Category" value="api" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1045" name="MultiplyTwoNumbersApi(&quot;12&quot;,&quot;6&quot;,&quot;72&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(&quot;12&quot;,&quot;6&quot;,&quot;72&quot;,System.String[])" methodname="MultiplyTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="608442110" result="Failed" label="Error" start-time="2016-06-07 18:25:31Z" end-time="2016-06-07 18:25:33Z" duration="2.021811" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 58]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 12 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("12") (0.0s)
And I have set 6 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("6") (0.0s)
When I send the "multiply" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 72 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1046" name="MultiplyTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;100&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;100&quot;,System.String[])" methodname="MultiplyTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="674926834" result="Failed" label="Error" start-time="2016-06-07 18:25:33Z" end-time="2016-06-07 18:25:35Z" duration="2.017676" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 58]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -20 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-20") (0.0s)
And I have set -5 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-5") (0.0s)
When I send the "multiply" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 100 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1047" name="MultiplyTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;-540&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;-540&quot;,System.String[])" methodname="MultiplyTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="502868772" result="Failed" label="Error" start-time="2016-06-07 18:25:35Z" end-time="2016-06-07 18:25:37Z" duration="2.017018" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 58]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 180 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("180") (0.0s)
And I have set -3 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-3") (0.0s)
When I send the "multiply" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -540 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1048" name="MultiplyTwoNumbersApi(&quot;-8&quot;,&quot;2&quot;,&quot;-16&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(&quot;-8&quot;,&quot;2&quot;,&quot;-16&quot;,System.String[])" methodname="MultiplyTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="953557922" result="Failed" label="Error" start-time="2016-06-07 18:25:37Z" end-time="2016-06-07 18:25:39Z" duration="2.017739" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.MultiplyTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 58]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -8 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-8") (0.0s)
And I have set 2 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("2") (0.0s)
When I send the "multiply" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -16 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
            <test-suite type="ParameterizedMethod" id="0-1039" name="SubstractTwoNumbersApi" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2016-06-07 18:25:39Z" end-time="2016-06-07 18:25:51Z" duration="12.117244" total="6" passed="0" failed="6" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Substract two numbers api" />
                <property name="Category" value="api" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1033" name="SubstractTwoNumbersApi(&quot;12&quot;,&quot;5&quot;,&quot;7&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(&quot;12&quot;,&quot;5&quot;,&quot;7&quot;,System.String[])" methodname="SubstractTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="193735939" result="Failed" label="Error" start-time="2016-06-07 18:25:39Z" end-time="2016-06-07 18:25:41Z" duration="2.022284" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 28]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 12 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("12") (0.0s)
And I have set 5 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("5") (0.0s)
When I send the "substract" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 7 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1034" name="SubstractTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;-15&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(&quot;-20&quot;,&quot;-5&quot;,&quot;-15&quot;,System.String[])" methodname="SubstractTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1390597427" result="Failed" label="Error" start-time="2016-06-07 18:25:41Z" end-time="2016-06-07 18:25:43Z" duration="2.020717" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 28]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -20 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-20") (0.0s)
And I have set -5 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-5") (0.0s)
When I send the "substract" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -15 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1035" name="SubstractTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;183&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(&quot;180&quot;,&quot;-3&quot;,&quot;183&quot;,System.String[])" methodname="SubstractTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="875415367" result="Failed" label="Error" start-time="2016-06-07 18:25:43Z" end-time="2016-06-07 18:25:45Z" duration="2.016894" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 28]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 180 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("180") (0.0s)
And I have set -3 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("-3") (0.0s)
When I send the "substract" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 183 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1036" name="SubstractTwoNumbersApi(&quot;-24&quot;,&quot;32&quot;,&quot;-56&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(&quot;-24&quot;,&quot;32&quot;,&quot;-56&quot;,System.String[])" methodname="SubstractTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1231727827" result="Failed" label="Error" start-time="2016-06-07 18:25:45Z" end-time="2016-06-07 18:25:47Z" duration="2.021383" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 28]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -24 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-24") (0.0s)
And I have set 32 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("32") (0.0s)
When I send the "substract" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -56 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1037" name="SubstractTwoNumbersApi(&quot;-1123&quot;,&quot;2&quot;,&quot;-1125&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(&quot;-1123&quot;,&quot;2&quot;,&quot;-1125&quot;,System.String[])" methodname="SubstractTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="52758991" result="Failed" label="Error" start-time="2016-06-07 18:25:47Z" end-time="2016-06-07 18:25:49Z" duration="2.016050" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 28]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set -1123 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("-1123") (0.0s)
And I have set 2 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("2") (0.0s)
When I send the "substract" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be -1125 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1038" name="SubstractTwoNumbersApi(&quot;2512&quot;,&quot;51&quot;,&quot;2461&quot;,System.String[])" fullname="AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(&quot;2512&quot;,&quot;51&quot;,&quot;2461&quot;,System.String[])" methodname="SubstractTwoNumbersApi" classname="AccptanceTests.Api.Features.ApiOperationsFeature" runstate="Runnable" seed="1923791459" result="Failed" label="Error" start-time="2016-06-07 18:25:49Z" end-time="2016-06-07 18:25:51Z" duration="2.018186" asserts="0">
                <failure>
                  <message><![CDATA[Newtonsoft.Json.JsonSerializationException : No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.]]></message>
                  <stack-trace><![CDATA[   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AccptanceTests.Api.Steps.ApiOperations.WhenISendTheRequest(String requestUrl) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Steps\ApiOperations.cs:line 45
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Api.Features.ApiOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature.cs:line 0
   at AccptanceTests.Api.Features.ApiOperationsFeature.SubstractTwoNumbersApi(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Api\Features\ApiOperations.feature:line 28]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have set 2512 in a request as first number
-> done: ApiOperations.GivenIHaveSetInARequestAsFirstNumber("2512") (0.0s)
And I have set 51 in a request as second number
-> done: ApiOperations.GivenIHaveSetInARequestAsSecondNumber("51") (0.0s)
When I send the "substract" request
-> error: No JSON content found and type 'System.Double' is not nullable. Path '', line 0, position 0.
Then the result should be 2461 on the response
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
          </test-suite>
        </test-suite>
      </test-suite>
      <test-suite type="TestSuite" id="0-1052" name="Web" fullname="AccptanceTests.Web" runstate="Runnable" testcasecount="20" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:28:21Z" duration="193.830169" total="20" passed="0" failed="20" inconclusive="0" skipped="0" asserts="0">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestSuite" id="0-1053" name="Features" fullname="AccptanceTests.Web.Features" runstate="Runnable" testcasecount="20" result="Failed" site="Child" start-time="2016-06-07 18:25:07Z" end-time="2016-06-07 18:28:21Z" duration="193.830147" total="20" passed="0" failed="20" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-suite type="TestFixture" id="0-1000" name="WebOperationsFeature" fullname="AccptanceTests.Web.Features.WebOperationsFeature" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" testcasecount="20" result="Failed" site="Child" start-time="2016-06-07 18:25:51Z" end-time="2016-06-07 18:28:21Z" duration="150.077762" total="20" passed="0" failed="20" inconclusive="0" skipped="0" asserts="0">
            <properties>
              <property name="Description" value="Web Operations" />
            </properties>
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
            </failure>
            <test-suite type="ParameterizedMethod" id="0-1007" name="AddTwoNumbers" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2016-06-07 18:25:51Z" end-time="2016-06-07 18:26:43Z" duration="52.386168" total="6" passed="0" failed="6" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Add two numbers" />
                <property name="Category" value="web" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1001" name="AddTwoNumbers(&quot;12&quot;,&quot;5&quot;,&quot;17&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(&quot;12&quot;,&quot;5&quot;,&quot;17&quot;,System.String[])" methodname="AddTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="798259755" result="Failed" label="Error" start-time="2016-06-07 18:25:51Z" end-time="2016-06-07 18:26:08Z" duration="17.664129" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 15]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (17.3s)
Given I have entered 12 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "add" button
-> skipped because of previous errors
And I have entered 5 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 17 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1002" name="AddTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;-25&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;-25&quot;,System.String[])" methodname="AddTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1396928079" result="Failed" label="Error" start-time="2016-06-07 18:26:08Z" end-time="2016-06-07 18:26:15Z" duration="6.967152" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 15]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.7s)
Given I have entered -20 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "add" button
-> skipped because of previous errors
And I have entered -5 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -25 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1003" name="AddTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;177&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;177&quot;,System.String[])" methodname="AddTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1630670862" result="Failed" label="Error" start-time="2016-06-07 18:26:15Z" end-time="2016-06-07 18:26:23Z" duration="7.152444" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 15]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.8s)
Given I have entered 180 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "add" button
-> skipped because of previous errors
And I have entered -3 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 177 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1004" name="AddTwoNumbers(&quot;-24&quot;,&quot;32&quot;,&quot;8&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(&quot;-24&quot;,&quot;32&quot;,&quot;8&quot;,System.String[])" methodname="AddTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="575529885" result="Failed" label="Error" start-time="2016-06-07 18:26:23Z" end-time="2016-06-07 18:26:29Z" duration="6.949406" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 15]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.8s)
Given I have entered -24 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "add" button
-> skipped because of previous errors
And I have entered 32 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 8 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1005" name="AddTwoNumbers(&quot;-1123&quot;,&quot;2&quot;,&quot;-1121&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(&quot;-1123&quot;,&quot;2&quot;,&quot;-1121&quot;,System.String[])" methodname="AddTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="993609143" result="Failed" label="Error" start-time="2016-06-07 18:26:29Z" end-time="2016-06-07 18:26:36Z" duration="6.825806" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 15]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -1123 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "add" button
-> skipped because of previous errors
And I have entered 2 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -1121 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1006" name="AddTwoNumbers(&quot;2512&quot;,&quot;51&quot;,&quot;2563&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(&quot;2512&quot;,&quot;51&quot;,&quot;2563&quot;,System.String[])" methodname="AddTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="332551961" result="Failed" label="Error" start-time="2016-06-07 18:26:36Z" end-time="2016-06-07 18:26:43Z" duration="6.817256" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.AddTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 15]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 2512 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "add" button
-> skipped because of previous errors
And I have entered 51 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 2563 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
            <test-suite type="ParameterizedMethod" id="0-1019" name="DivideTwoNumbers" fullname="AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-06-07 18:26:43Z" end-time="2016-06-07 18:27:10Z" duration="27.256846" total="4" passed="0" failed="4" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Divide two numbers" />
                <property name="Category" value="web" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1015" name="DivideTwoNumbers(&quot;12&quot;,&quot;6&quot;,&quot;2&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(&quot;12&quot;,&quot;6&quot;,&quot;2&quot;,System.String[])" methodname="DivideTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1658039280" result="Failed" label="Error" start-time="2016-06-07 18:26:43Z" end-time="2016-06-07 18:26:50Z" duration="6.806474" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 49]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 12 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "divide" button
-> skipped because of previous errors
And I have entered 6 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 2 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1016" name="DivideTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;4&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;4&quot;,System.String[])" methodname="DivideTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1272539657" result="Failed" label="Error" start-time="2016-06-07 18:26:50Z" end-time="2016-06-07 18:26:57Z" duration="6.828665" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 49]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -20 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "divide" button
-> skipped because of previous errors
And I have entered -5 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 4 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1017" name="DivideTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;-60&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;-60&quot;,System.String[])" methodname="DivideTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="591261833" result="Failed" label="Error" start-time="2016-06-07 18:26:57Z" end-time="2016-06-07 18:27:04Z" duration="6.785680" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 49]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 180 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "divide" button
-> skipped because of previous errors
And I have entered -3 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -60 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1018" name="DivideTwoNumbers(&quot;-8&quot;,&quot;2&quot;,&quot;-4&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(&quot;-8&quot;,&quot;2&quot;,&quot;-4&quot;,System.String[])" methodname="DivideTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="118089422" result="Failed" label="Error" start-time="2016-06-07 18:27:04Z" end-time="2016-06-07 18:27:10Z" duration="6.834729" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.DivideTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 49]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -8 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "divide" button
-> skipped because of previous errors
And I have entered 2 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -4 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
            <test-suite type="ParameterizedMethod" id="0-1024" name="MultiplyTwoNumbers" fullname="AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2016-06-07 18:27:10Z" end-time="2016-06-07 18:27:40Z" duration="29.620656" total="4" passed="0" failed="4" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Multiply two numbers" />
                <property name="Category" value="web" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1020" name="MultiplyTwoNumbers(&quot;12&quot;,&quot;6&quot;,&quot;72&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(&quot;12&quot;,&quot;6&quot;,&quot;72&quot;,System.String[])" methodname="MultiplyTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1620750620" result="Failed" label="Error" start-time="2016-06-07 18:27:10Z" end-time="2016-06-07 18:27:17Z" duration="6.825761" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 64]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 12 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "multiply" button
-> skipped because of previous errors
And I have entered 6 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 72 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1021" name="MultiplyTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;100&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;100&quot;,System.String[])" methodname="MultiplyTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1152481947" result="Failed" label="Error" start-time="2016-06-07 18:27:17Z" end-time="2016-06-07 18:27:24Z" duration="6.794763" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 64]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -20 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "multiply" button
-> skipped because of previous errors
And I have entered -5 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 100 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1022" name="MultiplyTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;-540&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;-540&quot;,System.String[])" methodname="MultiplyTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1328488278" result="Failed" label="Error" start-time="2016-06-07 18:27:24Z" end-time="2016-06-07 18:27:33Z" duration="9.175328" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 64]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (9.0s)
Given I have entered 180 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "multiply" button
-> skipped because of previous errors
And I have entered -3 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -540 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1023" name="MultiplyTwoNumbers(&quot;-8&quot;,&quot;2&quot;,&quot;-16&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(&quot;-8&quot;,&quot;2&quot;,&quot;-16&quot;,System.String[])" methodname="MultiplyTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="2083519019" result="Failed" label="Error" start-time="2016-06-07 18:27:33Z" end-time="2016-06-07 18:27:40Z" duration="6.823508" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.MultiplyTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 64]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -8 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "multiply" button
-> skipped because of previous errors
And I have entered 2 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -16 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
            <test-suite type="ParameterizedMethod" id="0-1014" name="SubstractTwoNumbers" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers" runstate="Runnable" testcasecount="6" result="Failed" site="Child" start-time="2016-06-07 18:27:40Z" end-time="2016-06-07 18:28:21Z" duration="40.812015" total="6" passed="0" failed="6" inconclusive="0" skipped="0" asserts="0">
              <properties>
                <property name="Description" value="Substract two numbers" />
                <property name="Category" value="web" />
              </properties>
              <failure>
                <message><![CDATA[One or more child tests had errors]]></message>
              </failure>
              <test-case id="0-1008" name="SubstractTwoNumbers(&quot;12&quot;,&quot;5&quot;,&quot;7&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(&quot;12&quot;,&quot;5&quot;,&quot;7&quot;,System.String[])" methodname="SubstractTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="2113917196" result="Failed" label="Error" start-time="2016-06-07 18:27:40Z" end-time="2016-06-07 18:27:47Z" duration="6.789973" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 32]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 12 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "substract" button
-> skipped because of previous errors
And I have entered 5 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 7 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1009" name="SubstractTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;-15&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(&quot;-20&quot;,&quot;-5&quot;,&quot;-15&quot;,System.String[])" methodname="SubstractTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="813987263" result="Failed" label="Error" start-time="2016-06-07 18:27:47Z" end-time="2016-06-07 18:27:54Z" duration="6.795338" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 32]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -20 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "substract" button
-> skipped because of previous errors
And I have entered -5 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -15 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1010" name="SubstractTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;183&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(&quot;180&quot;,&quot;-3&quot;,&quot;183&quot;,System.String[])" methodname="SubstractTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1460656856" result="Failed" label="Error" start-time="2016-06-07 18:27:54Z" end-time="2016-06-07 18:28:00Z" duration="6.848422" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 32]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 180 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "substract" button
-> skipped because of previous errors
And I have entered -3 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 183 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1011" name="SubstractTwoNumbers(&quot;-24&quot;,&quot;32&quot;,&quot;-56&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(&quot;-24&quot;,&quot;32&quot;,&quot;-56&quot;,System.String[])" methodname="SubstractTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="1896201078" result="Failed" label="Error" start-time="2016-06-07 18:28:00Z" end-time="2016-06-07 18:28:07Z" duration="6.792234" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 32]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -24 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "substract" button
-> skipped because of previous errors
And I have entered 32 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -56 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1012" name="SubstractTwoNumbers(&quot;-1123&quot;,&quot;2&quot;,&quot;-1125&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(&quot;-1123&quot;,&quot;2&quot;,&quot;-1125&quot;,System.String[])" methodname="SubstractTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="213326761" result="Failed" label="Error" start-time="2016-06-07 18:28:07Z" end-time="2016-06-07 18:28:14Z" duration="6.814423" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 32]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered -1123 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "substract" button
-> skipped because of previous errors
And I have entered 2 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be -1125 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
              <test-case id="0-1013" name="SubstractTwoNumbers(&quot;2512&quot;,&quot;51&quot;,&quot;2461&quot;,System.String[])" fullname="AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(&quot;2512&quot;,&quot;51&quot;,&quot;2461&quot;,System.String[])" methodname="SubstractTwoNumbers" classname="AccptanceTests.Web.Features.WebOperationsFeature" runstate="Runnable" seed="421480137" result="Failed" label="Error" start-time="2016-06-07 18:28:14Z" end-time="2016-06-07 18:28:21Z" duration="6.769710" asserts="0">
                <failure>
                  <message><![CDATA[OpenQA.Selenium.NoSuchElementException : Could not find element by: By.Id: number1]]></message>
                  <stack-trace><![CDATA[   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at AccptanceTests.Web.Steps.WebOperations.GivenIHaveEnteredIntoTheCalculatorAsFirstNumber(Int32 number1) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Steps\WebOperations.cs:line 24
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at AccptanceTests.Web.Features.WebOperationsFeature.ScenarioCleanup() in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations1.feature.cs:line 0
   at AccptanceTests.Web.Features.WebOperationsFeature.SubstractTwoNumbers(String number1, String number2, String result, String[] exampleTags) in C:\Users\Federito\Cursos\BddBelax\MathOperations\MathOperations.AcceptanceTests\Web\Features\WebOperations.feature:line 32]]></stack-trace>
                </failure>
                <output><![CDATA[Given I have navigated to the calculators page
-> done: WebOperations.GivenIHaveNavigatedToTheCalculatorsPage() (6.6s)
Given I have entered 2512 into the calculator as first number
-> error: Could not find element by: By.Id: number1
And I have pressed the "substract" button
-> skipped because of previous errors
And I have entered 51 into the calculator as second number
-> skipped because of previous errors
When I press the equals button
-> skipped because of previous errors
Then the result should be 2461 on the screen
-> skipped because of previous errors
]]></output>
              </test-case>
            </test-suite>
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>